src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $subtitle = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $published_at = null;

    #[ORM\Column(length: 13)]
    private ?string $ISBN = null;

    #[ORM\Column(length: 255)]
    private ?string $language = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cover = null;

    #[ORM\Column]
    private ?int $pages = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(?string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeImmutable $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getISBN(): ?string
    {
        return $this->ISBN;
    }

    public function setISBN(string $ISBN): self
    {
        $this->ISBN = $ISBN;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(string $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getPages(): ?int
    {
        return $this->pages;
    }

    public function setPages(int $pages): self
    {
        $this->pages = $pages;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('subtitle')
            ->add('published_at')
            ->add('ISBN')
            ->add('language')
            ->add('cover')
            ->add('pages')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/book')]
class BookController extends AbstractController
{
    #[Route('/', name: 'app_book_index', methods: ['GET'])]
    public function index(BookRepository $bookRepository): Response
    {
        return $this->render('book/index.html.twig', [
            'books' => $bookRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_book_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BookRepository $bookRepository): Response
    {
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bookRepository->save($book, true);

            return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('book/new.html.twig', [
            'book' => $book,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_book_show', methods: ['GET'])]
    public function show(Book $book): Response
    {
        return $this->render('book/show.html.twig', [
            'book' => $book,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_book_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Book $book, BookRepository $bookRepository): Response
    {
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bookRepository->save($book, true);

            return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('book/edit.html.twig', [
            'book' => $book,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_book_delete', methods: ['POST'])]
    public function delete(Request $request, Book $book, BookRepository $bookRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$book->getId(), $request->request->get('_token'))) {
            $bookRepository->remove($book, true);
        }

        return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function home(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/test', name: 'test')]
    public function test(): Response
    {
        return $this->render('home/test.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}


    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap.min.css') }}">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{{ asset('css/responsive.css') }}">
    <!-- fevicon -->
    <link rel="icon" href="images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{{ asset('css/jquery.mCustomScrollbar.min.css') }}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Righteous&display=swap" rel="stylesheet">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="{{ asset('css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/owl.theme.default.min.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
        media="screen">







    {% block stylesheets %}
    {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
    {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>

<body>
    <div class="header_section">
        <div class="header_main">
            <div class="mobile_menu">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="logo_mobile"><a href="{{ path('app_home') }}"><img
                                src="{{ asset('images/logo.png') }}"></a></div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_home') }}">Accueil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_book_index') }}">Livres</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">#</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " href="#">#</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " href="#">#</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
            <div class="container-fluid">
                <div class="logo"><a href="{{ path('app_home') }}"><img src="{{ asset('images/logo.png') }}"></a></div>
                <div class="menu_main">
                    <ul>
                        <li class="active"><a href="{{ path('app_home') }}">Accueil</a></li>
                        <li><a href="{{ path('app_book_index') }}">Livres</a></li>
                        <li><a href="#">#</a></li>
                        <li><a href="#">#</a></li>
                        <li><a href="#">#</a></li>
                    </ul>
                </div>
            </div>
        </div>
        {% block body %}{% endblock %}

        <!-- footer section start -->
        <div class="footer_section layout_padding">
            <div class="container">
                <div class="input_btn_main">
                    <input type="text" class="mail_text" placeholder="Enter your email" name="Enter your email">
                    <div class="subscribe_bt"><a href="#">Subscribe</a></div>
                </div>
                <div class="location_main">
                    <div class="call_text"><img src="{{ asset('images/call-icon.png') }}"></div>
                    <div class="call_text"><a href="#">Call +01 1234567890</a></div>
                    <div class="call_text"><img src="{{ asset('images/mail-icon.png') }}"></div>
                    <div class="call_text"><a href="#">demo@gmail.com</a></div>
                </div>
                <div class="social_icon">
                    <ul>
                        <li><a href="#"><img src="{{ asset('images/fb-icon.png') }}"></a></li>
                        <li><a href="#"><img src="{{ asset('images/twitter-icon.png') }}"></a></li>
                        <li><a href="#"><img src="{{ asset('images/linkedin-icon.png') }}"></a></li>
                        <li><a href="#"><img src="{{ asset('images/instagram-icon.png') }}"></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- footer section end -->
        <!-- copyright section start -->
        <div class="copyright_section">
            <div class="container">
                <p class="copyright_text">2020 All Rights Reserved. Design by <a href="https://html.design">Free html Templates</a> Distributed by <a href="https://themewagon.com">ThemeWagon</a></p>
            </div>
        </div>
</body>

</html>

templates/book/_delete_form.html.twig
<form method="post" action="{{ path('app_book_delete', {'id': book.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="btn">Delete</button>
</form>

templates/book/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Book{% endblock %}

{% block body %}
    <h1>Edit Book</h1>

    {{ include('book/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_book_index') }}">back to list</a>

    {{ include('book/_delete_form.html.twig') }}
{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book index{% endblock %}

{% block body %}
    <div class="services_section layout_padding">
        <div class="container">
            <h1 class="services_taital">Services </h1>
            <p class="services_text">There are many variations of passages of Lorem Ipsum available, but the majority have
                suffered alteration</p>
            <div class="services_section_2">
                <div class="row">
                    <div class="col-md-4">
                        <div>
                            <img src="{{ asset('images/img-1.png') }}" class="services_img">
                        </div>
                        <div class="btn_main">
                            <a href="#">Rafting</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div>
                            <img src="{{ asset('images/img-2.png') }}" class="services_img">
                        </div>
                        <div class="btn_main active">
                            <a href="#">Hiking</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div>
                            <img src="{{ asset('images/img-3.png') }}" class="services_img">
                        </div>
                        <div class="btn_main">
                            <a href="#">Camping</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>











<h1>Book index</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Subtitle</th>
            <th>Published_at</th>
            <th>ISBN</th>
            <th>Language</th>
            <th>Cover</th>
            <th>Pages</th>
            <th>Description</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
            <td>{{ book.id }}</td>
            <td>{{ book.title }}</td>
            <td>{{ book.subtitle }}</td>
            <td>{{ book.publishedAt ? book.publishedAt|date('Y-m-d H:i:s') : '' }}</td>
            <td>{{ book.ISBN }}</td>
            <td>{{ book.language }}</td>
            <td>{{ book.cover }}</td>
            <td>{{ book.pages }}</td>
            <td>{{ book.description }}</td>
            <td>
                <a href="{{ path('app_book_show', {'id': book.id}) }}">show</a>
                <a href="{{ path('app_book_edit', {'id': book.id}) }}">edit</a>
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="10">no records found</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{{ path('app_book_new') }}">Create new</a>
{% endblock %}

templates/book/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Book{% endblock %}

{% block body %}
    <h1>Create new Book</h1>

    {{ include('book/_form.html.twig') }}

    <a href="{{ path('app_book_index') }}">back to list</a>
{% endblock %}

templates/book/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book{% endblock %}

{% block body %}
    <h1>Book</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ book.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ book.title }}</td>
            </tr>
            <tr>
                <th>Subtitle</th>
                <td>{{ book.subtitle }}</td>
            </tr>
            <tr>
                <th>Published_at</th>
                <td>{{ book.publishedAt ? book.publishedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>ISBN</th>
                <td>{{ book.ISBN }}</td>
            </tr>
            <tr>
                <th>Language</th>
                <td>{{ book.language }}</td>
            </tr>
            <tr>
                <th>Cover</th>
                <td>{{ book.cover }}</td>
            </tr>
            <tr>
                <th>Pages</th>
                <td>{{ book.pages }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ book.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_book_index') }}">back to list</a>

    <a href="{{ path('app_book_edit', {'id': book.id}) }}">edit</a>

    {{ include('book/_delete_form.html.twig') }}
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
<!-- banner section start -->
<div class="banner_section layout_padding">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container">
                    <h1 class="banner_taital">Adventure</h1>
                    <p class="banner_text">There are many variations of passages of Lorem Ipsum available, but the
                        majority have sufferedThere are ma available, but the majority have suffered</p>
                    <div class="read_bt"><a href="#">Get A Quote</a></div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <h1 class="banner_taital">Adventure</h1>
                    <p class="banner_text">There are many variations of passages of Lorem Ipsum available, but the
                        majority have sufferedThere are ma available, but the majority have suffered</p>
                    <div class="read_bt"><a href="#">Get A Quote</a></div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <h1 class="banner_taital">Adventure</h1>
                    <p class="banner_text">There are many variations of passages of Lorem Ipsum available, but the
                        majority have sufferedThere are ma available, but the majority have suffered</p>
                    <div class="read_bt"><a href="#">Get A Quote</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/home/test.html.twig
{% extends "base.html.twig" %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}

<div class="about_section layout_padding" style="background-color: white; margin: 20px 0 0 0">
    <div class="container-fluid">
       <div class="row">
          <div class="col-md-6">
             <div class="about_taital_main">
                <h1 class="about_taital">About Us</h1>
                <p class="about_text">There are many variations of passages of Lorem Ipsum available, but the majority
                   have suffered alteration in some form, by injected humour, or randomised words which don't look
                   even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure
                   there isn't anything embarrassing hidden in the middle of text. All </p>
                <div class="readmore_bt"><a href="#">Read More</a></div>
             </div>
          </div>
          <div class="col-md-6 padding_right_0">
             <div><img src="images/about-img.png" class="about_img"></div>
          </div>
       </div>
    </div>
 </div>
{% endblock %}